name: ci

permissions:
  contents: read        # allow checkout & metadata-action to read repo
  id-token: write       # needed by docker/metadata-action v4
  packages: write

on:
  push:
    branches:
      - 'main'
      - 'staging'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ghcr.io/instantsys-labs/opensign
            dockerfile: apps/OpenSign/Dockerhubfile
          - image: ghcr.io/instantsys-labs/opensignserver
            dockerfile: apps/OpenSignServer/Dockerhubfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      -
        name: Debug - List files opensign
        run: ls -R apps/OpenSign/  # Adjust the path as needed
      -
        name: Debug - List files opensignserver
        run: ls -R apps/OpenSignServer/  # Adjust the path as needed  
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
